name: Build and Deploy NWNX4 Docker Image

on:
  release:
    types: [released]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Release URL as Environment Variable
        run: echo "RELEASE_URL=${{ github.event.release.assets[0].browser_download_url }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t nwn2dev/nwnx4 -f docker/nwnx4/Dockerfile --build-arg RELEASE_URL=${RELEASE_URL} .
          docker tag nwn2dev/nwnx4 nwn2dev/nwnx4:${{ github.event.release.tag_name }}
          docker push nwn2dev/nwnx4:${{ github.event.release.tag_name }}