name: NWNX4 Docker Image CI

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to use'
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Release URL and Tag as Environment Variables
        run: |
          # If triggered by workflow_dispatch, use the latest release
          if [ -n "${{ github.event.inputs.release_tag }}" ]; then
            release_info=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.inputs.release_tag }})
            export RELEASE_URL=$(echo $release_info | jq -r '.assets[0].browser_download_url')
            export TAG_NAME=$(echo $release_info | jq -r '.tag_name')
          else
            export RELEASE_URL=${{ github.event.release.assets[0].browser_download_url }}
            export TAG_NAME=${{ github.event.release.tag_name }}
          fi
          
          echo "RELEASE_URL=${RELEASE_URL}" >> $GITHUB_ENV
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t nwn2dev/nwnx4 -f docker/nwnx4/Dockerfile --build-arg RELEASE_URL=${RELEASE_URL} .
          docker tag nwn2dev/nwnx4 nwn2dev/nwnx4:${TAG_NAME}
          docker push nwn2dev/nwnx4:${TAG_NAME}